[package]
name = "gpt"
version = "0.1.0"
edition = "2024"

[dependencies]
ferrotorch-core = "0.6.2"
ferrotorch-nn = "0.6.2"
ferrotorch = { version = "0.6.2", features = ["tokenize", "gpu"] }
cudarc = { version = "0.19", features = ["cuda-12060"] }
libloading = "0.9"

[patch.crates-io]
ferrotorch       = { path = "../ferrotorch/ferrotorch" }
ferrotorch-core  = { path = "../ferrotorch/ferrotorch-core" }
ferrotorch-gpu   = { path = "../ferrotorch/ferrotorch-gpu" }
ferrotorch-nn    = { path = "../ferrotorch/ferrotorch-nn" }
ferrotorch-optim = { path = "../ferrotorch/ferrotorch-optim" }